-- AlterTable
ALTER TABLE "Item" ADD COLUMN IF NOT EXISTS "donatedToDiscartMe" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Item" ADD COLUMN IF NOT EXISTS "discartItemId" INTEGER;
ALTER TABLE "Item" ADD COLUMN IF NOT EXISTS "donatedAt" TIMESTAMP(3);

