import { registerEnumType } from '@nestjs/graphql';

export enum LogAction {
    USER_LOGIN = "USER_LOGIN",
    USER_LOGOUT = "USER_LOGOUT",
    ITEM_CREATED = "ITEM_CREATED",
    ITEM_UPDATED = "ITEM_UPDATED",
    ITEM_DELETED = "ITEM_DELETED",
    CONTAINER_CREATED = "CONTAINER_CREATED",
    CONTAINER_DELETED = "CONTAINER_DELETED",
    BUTTON_CLICKED = "BUTTON_CLICKED",
    PAGE_VIEWED = "PAGE_VIEWED",
    SEARCH_USED = "SEARCH_USED",
    CUSTOM_ACTION = "CUSTOM_ACTION",
    REQUEST_PASSWORD_RESET = "REQUEST_PASSWORD_RESET",
    PASSWORD_RESET = "PASSWORD_RESET",
    USER_REGISTERED = "USER_REGISTERED",
    USER_PROFILE_UPDATED = "USER_PROFILE_UPDATED",
    USER_DELETED = "USER_DELETED",
    STORAGE_CREATED = "STORAGE_CREATED",
    STORAGE_DELETED = "STORAGE_DELETED",
    SUBCONTRACTOR_CREATED = "SUBCONTRACTOR_CREATED",
    SUBCONTRACTOR_UPDATED = "SUBCONTRACTOR_UPDATED",
    SUBCONTRACTOR_DELETED = "SUBCONTRACTOR_DELETED",
    SUBCONTRACTOR_VIEWED = "SUBCONTRACTOR_VIEWED"
}


registerEnumType(LogAction, { name: 'LogAction', description: undefined })
