import { UserWhereInput } from './user-where.input';
import { StringFilter } from '../prisma/string-filter.input';
import { StringNullableFilter } from '../prisma/string-nullable-filter.input';
import { BoolFilter } from '../prisma/bool-filter.input';
import { EnumRoleFilter } from '../prisma/enum-role-filter.input';
import { DateTimeFilter } from '../prisma/date-time-filter.input';
import { DateTimeNullableFilter } from '../prisma/date-time-nullable-filter.input';
import { StorageMemberListRelationFilter } from '../storage-member/storage-member-list-relation-filter.input';
import { LogListRelationFilter } from '../log/log-list-relation-filter.input';
import { ProjectListRelationFilter } from '../project/project-list-relation-filter.input';
import { ConstructionLogListRelationFilter } from '../construction-log/construction-log-list-relation-filter.input';
import { LogCommentListRelationFilter } from '../log-comment/log-comment-list-relation-filter.input';
import { LogCommentReplyListRelationFilter } from '../log-comment-reply/log-comment-reply-list-relation-filter.input';
import { PermitInspectionListRelationFilter } from '../permit-inspection/permit-inspection-list-relation-filter.input';
import { MaterialEntryListRelationFilter } from '../material-entry/material-entry-list-relation-filter.input';
import { DiscartItemListRelationFilter } from '../discart-item/discart-item-list-relation-filter.input';
export declare class UserWhereUniqueInput {
    id?: number;
    email?: string;
    AND?: Array<UserWhereInput>;
    OR?: Array<UserWhereInput>;
    NOT?: Array<UserWhereInput>;
    password?: StringFilter;
    firstName?: StringFilter;
    lastName?: StringFilter;
    nickname?: StringNullableFilter;
    public?: BoolFilter;
    role?: EnumRoleFilter;
    emailVerified?: BoolFilter;
    profilePicture?: StringNullableFilter;
    about?: StringNullableFilter;
    createdAt?: DateTimeFilter;
    updatedAt?: DateTimeFilter;
    isPremium?: BoolFilter;
    subscriptionId?: StringNullableFilter;
    expiresAt?: DateTimeNullableFilter;
    willExpireAt?: DateTimeNullableFilter;
    apartment?: StringNullableFilter;
    isApprovedResident?: BoolFilter;
    isAdmin?: BoolFilter;
    storageMemberships?: StorageMemberListRelationFilter;
    logs?: LogListRelationFilter;
    projectResponsible?: ProjectListRelationFilter;
    constructionLogs?: ConstructionLogListRelationFilter;
    logComments?: LogCommentListRelationFilter;
    logCommentReplies?: LogCommentReplyListRelationFilter;
    responsibleInspections?: PermitInspectionListRelationFilter;
    receivedMaterials?: MaterialEntryListRelationFilter;
    discartItems?: DiscartItemListRelationFilter;
}
