import { SortOrder } from '../prisma/sort-order.enum';
import { SortOrderInput } from '../prisma/sort-order.input';
import { StorageMemberOrderByRelationAggregateInput } from '../storage-member/storage-member-order-by-relation-aggregate.input';
import { LogOrderByRelationAggregateInput } from '../log/log-order-by-relation-aggregate.input';
import { ProjectOrderByRelationAggregateInput } from '../project/project-order-by-relation-aggregate.input';
import { ConstructionLogOrderByRelationAggregateInput } from '../construction-log/construction-log-order-by-relation-aggregate.input';
import { LogCommentOrderByRelationAggregateInput } from '../log-comment/log-comment-order-by-relation-aggregate.input';
import { LogCommentReplyOrderByRelationAggregateInput } from '../log-comment-reply/log-comment-reply-order-by-relation-aggregate.input';
import { PermitInspectionOrderByRelationAggregateInput } from '../permit-inspection/permit-inspection-order-by-relation-aggregate.input';
import { MaterialEntryOrderByRelationAggregateInput } from '../material-entry/material-entry-order-by-relation-aggregate.input';
import { DiscartItemOrderByRelationAggregateInput } from '../discart-item/discart-item-order-by-relation-aggregate.input';
export declare class UserOrderByWithRelationInput {
    id?: keyof typeof SortOrder;
    email?: keyof typeof SortOrder;
    password?: keyof typeof SortOrder;
    firstName?: keyof typeof SortOrder;
    lastName?: keyof typeof SortOrder;
    nickname?: SortOrderInput;
    public?: keyof typeof SortOrder;
    role?: keyof typeof SortOrder;
    emailVerified?: keyof typeof SortOrder;
    profilePicture?: SortOrderInput;
    about?: SortOrderInput;
    createdAt?: keyof typeof SortOrder;
    updatedAt?: keyof typeof SortOrder;
    isPremium?: keyof typeof SortOrder;
    subscriptionId?: SortOrderInput;
    expiresAt?: SortOrderInput;
    willExpireAt?: SortOrderInput;
    apartment?: SortOrderInput;
    isApprovedResident?: keyof typeof SortOrder;
    isAdmin?: keyof typeof SortOrder;
    storageMemberships?: StorageMemberOrderByRelationAggregateInput;
    logs?: LogOrderByRelationAggregateInput;
    projectResponsible?: ProjectOrderByRelationAggregateInput;
    constructionLogs?: ConstructionLogOrderByRelationAggregateInput;
    logComments?: LogCommentOrderByRelationAggregateInput;
    logCommentReplies?: LogCommentReplyOrderByRelationAggregateInput;
    responsibleInspections?: PermitInspectionOrderByRelationAggregateInput;
    receivedMaterials?: MaterialEntryOrderByRelationAggregateInput;
    discartItems?: DiscartItemOrderByRelationAggregateInput;
}
