import { StringFieldUpdateOperationsInput } from '../prisma/string-field-update-operations.input';
import { NullableStringFieldUpdateOperationsInput } from '../prisma/nullable-string-field-update-operations.input';
import { BoolFieldUpdateOperationsInput } from '../prisma/bool-field-update-operations.input';
import { EnumRoleFieldUpdateOperationsInput } from '../prisma/enum-role-field-update-operations.input';
import { DateTimeFieldUpdateOperationsInput } from '../prisma/date-time-field-update-operations.input';
import { NullableDateTimeFieldUpdateOperationsInput } from '../prisma/nullable-date-time-field-update-operations.input';
import { StorageMemberUpdateManyWithoutUserNestedInput } from '../storage-member/storage-member-update-many-without-user-nested.input';
import { LogUpdateManyWithoutUserNestedInput } from '../log/log-update-many-without-user-nested.input';
import { ProjectUpdateManyWithoutResponsibleNestedInput } from '../project/project-update-many-without-responsible-nested.input';
import { LogCommentUpdateManyWithoutUserNestedInput } from '../log-comment/log-comment-update-many-without-user-nested.input';
import { LogCommentReplyUpdateManyWithoutUserNestedInput } from '../log-comment-reply/log-comment-reply-update-many-without-user-nested.input';
import { PermitInspectionUpdateManyWithoutResponsibleNestedInput } from '../permit-inspection/permit-inspection-update-many-without-responsible-nested.input';
import { MaterialEntryUpdateManyWithoutReceivedByNestedInput } from '../material-entry/material-entry-update-many-without-received-by-nested.input';
import { DiscartItemUpdateManyWithoutCreatedByNestedInput } from '../discart-item/discart-item-update-many-without-created-by-nested.input';
export declare class UserUpdateWithoutConstructionLogsInput {
    email?: StringFieldUpdateOperationsInput;
    password?: StringFieldUpdateOperationsInput;
    firstName?: StringFieldUpdateOperationsInput;
    lastName?: StringFieldUpdateOperationsInput;
    nickname?: NullableStringFieldUpdateOperationsInput;
    public?: BoolFieldUpdateOperationsInput;
    role?: EnumRoleFieldUpdateOperationsInput;
    emailVerified?: BoolFieldUpdateOperationsInput;
    profilePicture?: NullableStringFieldUpdateOperationsInput;
    about?: NullableStringFieldUpdateOperationsInput;
    createdAt?: DateTimeFieldUpdateOperationsInput;
    updatedAt?: DateTimeFieldUpdateOperationsInput;
    isPremium?: BoolFieldUpdateOperationsInput;
    subscriptionId?: NullableStringFieldUpdateOperationsInput;
    expiresAt?: NullableDateTimeFieldUpdateOperationsInput;
    willExpireAt?: NullableDateTimeFieldUpdateOperationsInput;
    apartment?: NullableStringFieldUpdateOperationsInput;
    isApprovedResident?: BoolFieldUpdateOperationsInput;
    isAdmin?: BoolFieldUpdateOperationsInput;
    storageMemberships?: StorageMemberUpdateManyWithoutUserNestedInput;
    logs?: LogUpdateManyWithoutUserNestedInput;
    projectResponsible?: ProjectUpdateManyWithoutResponsibleNestedInput;
    logComments?: LogCommentUpdateManyWithoutUserNestedInput;
    logCommentReplies?: LogCommentReplyUpdateManyWithoutUserNestedInput;
    responsibleInspections?: PermitInspectionUpdateManyWithoutResponsibleNestedInput;
    receivedMaterials?: MaterialEntryUpdateManyWithoutReceivedByNestedInput;
    discartItems?: DiscartItemUpdateManyWithoutCreatedByNestedInput;
}
